# see https://github.com/community-charts/helm-charts/blob/main/charts/cloudflared/values.yaml

cloudflared:
  tunnelConfig:
    name: tewing-home
  tunnelSecrets:
    existingConfigJsonFileSecret:
      name: config-json-file-secret
    existingPemFileSecret:
      name: cert-pem-file-secret
