# see https://github.com/dkoshkin/teslamate-helm-chart/blob/main/charts/teslamate/values.yaml

teslamate:
  controllers:
    main:
      containers:
        main:
          image:
            env:
              ENCRYPTION_KEY: "zzz111222333"
  remotePostgresql:
    enabled: true
    host: postgres.postgres.svc
    user: teslamate
    password: sdfsdfq3es
    database: teslamate
  ingress:
    enabled: true
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    path: /
    pathType: ImplementationSpecific
    hosts:
      - teslamate.example.com
    # tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
