# see https://github.com/dkoshkin/teslamate-helm-chart/blob/main/charts/teslamate/values.yaml

teslamate:
  envFromSecrets:
    - name: teslamate
  remotePostgresql:
    enabled: true
  ingress:
    enabled: true
    annotations: {}
    path: /
    hosts:
      - teslamate.example.com
    # tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
