# see https://github.com/dkoshkin/teslamate-helm-chart/blob/main/charts/teslamate/values.yaml

teslamate:
  env:
    LOG_LEVEL: "debug"
  envFromSecrets:
    - name: postgres-password
  remotePostgresql:
    enabled: true
    # secretName: postgres-credentials
    host: postgres-rw.postgres.svc
    user: teslamate
    # password: sdfsdfq3es
    database: teslamate

    # teslamate:
    #   image:
    #     tag: "2.2.0"
    #   envFromSecrets:
    #     - name: teslamate
    #   env:
    #     LOG_LEVEL: "debug"
    #   remotePostgresql:
    #     enabled: true
    #   ingress:
    #     enabled: true
    #     annotations: {}
    #     path: /
    #     hosts:
    #       - teslamate.example.com

    #     # tls: []
    #     #  - secretName: chart-example-tls
    #     #    hosts:
    #     #      - chart-example.local

    #   grafana:
    #     # override the image with the Teslama Grafana image that has the charts baked in
    #     image:
    #       repository: teslamate/grafana
    #       tag: latest
