# see https://github.com/dkoshkin/teslamate-helm-chart/blob/main/charts/teslamate/values.yaml

teslamate:
  remotePostgresql:
    enabled: true
    host: postgres.postgres.svc
    user: teslamate
    password: sdfsdfq3es
    database: teslamate
  ingress:
    enabled: true
