# see https://github.com/dkoshkin/teslamate-helm-chart/blob/main/charts/teslamate/values.yaml

teslamate:
  env:
    LOG_LEVEL: "debug"
  envFromSecrets:
    - name: encryption-key
  remotePostgresql:
    enabled: true
    secretName: postgres-credentials
  image:
    tag: latest

  ingress:
    enabled: true
    annotations: {}
    path: /
    hosts:
      - teslamate.example.com

  grafana:
    # https://github.com/grafana-community/helm-charts/blob/main/charts/grafana/values.yaml
    # https://github.com/teslamate-org/teslamate/blob/main/grafana/Dockerfile
    image:
      repository: teslamate/grafana
      tag: latest
