# see https://github.com/dkoshkin/teslamate-helm-chart/blob/main/charts/teslamate/values.yaml

teslamate:
  env:
    LOG_LEVEL: "debug"
  envFromSecrets:
    - name: postgres-password
    - name: encryption-key
  remotePostgresql:
    enabled: true
    host: postgres-rw.postgres.svc
    user: teslamate
    database: teslamate
  image:
    tag: "2.2.0"

  ingress:
    enabled: true
    annotations: {}
    path: /
    hosts:
      - teslamate.example.com

    # envFromSecrets:
    #   - name: teslamate
    # env:
    #   LOG_LEVEL: "debug"
    # remotePostgresql:
    #   enabled: true
    # tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  grafana:
    # override the image with the Teslama Grafana image that has the charts baked in
    image:
      repository: teslamate/grafana
      tag: latest
