postgres:
  customUser:
    # ## @param customUser.name Name of the custom user to be created
    # name: ""
    # ## @param customUser.database Name of the database to be created
    # database: ""
    # ## @param customUser.password Password to be used for the custom user
    # password: ""
    ## @param customUser.existingSecret Existing secret, in which username, password and database name are saved
    existingSecret: "teslamat-db-credentials"
    ## @param customUser.secretKeys Name of keys in existing secret to use the custom user name, password and database
    secretKeys:
      ## @param customUser.secretKeys.name Custom user name secret reference (set empty to fallback to customUser.name)
      name: "CUSTOM_USER"
      ## @param customUser.secretKeys.database Custom user database secret reference (set empty to fallback to customUser.database)
      database: "CUSTOM_DB"
      password: "CUSTOM_PASSWORD"
